#Prompt Example : My remote host <ip> httpd service failed to start with a control process error.
#Provide the diagnosis and fix for it. My remote host <ip> httpd service failed to start with
#a control process error. Provide the diagnosis and fix for it

---
- name: "Scenario 1: SELinux Port Denial"
  hosts: linux_vm
  become: yes
  tasks:

    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: present
        update_cache: true
        releasever: "10"

    - name: Configure Apache to listen on port 8088
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80'
        line: 'Listen 8088'

    - name: Ensure SELinux is enforcing
      ansible.builtin.command: setenforce 1
      changed_when: false

    - name: Restart Apache (expected to FAIL due to SELinux denial)
      ansible.builtin.systemd:
        name: httpd
        state: restarted
      failed_when: false



