#Prompt Example : The chronyd service on <ip> is crashing or failing to stay active.
#Job for chronyd.service failed because of an out-of-memory (OOM) siutation. Suggest a fix for this
---
- name: "Scenario 4: OOM Kill via Systemd"
  hosts: linux_vm
  become: yes
  tasks:
    - name: Set 1MB memory limit for chronyd
      ansible.builtin.command: systemctl set-property chronyd.service MemoryMax=1M
    - name: Restart service to trigger crash
      ansible.builtin.systemd:
        name: chronyd
        state: restarted