---
- name: "Scenario 2: Break SSH Permissions"
  hosts: linux_vm
  become: yes
  vars:
    test_user: testuser

  tasks:
    - name: Ensure testuser exists
      ansible.builtin.user:
        name: "{{ test_user }}"
        state: present
        shell: /bin/bash

    - name: Create .ssh folder with correct ownership
      ansible.builtin.file:
        path: "/home/{{ test_user }}/.ssh"
        state: directory
        owner: "{{ test_user }}"
        group: "{{ test_user }}"
        mode: '0700'

    - name: Create dummy authorized_keys file
      ansible.builtin.copy:
        dest: "/home/{{ test_user }}/.ssh/authorized_keys"
        content: "ssh-rsa AAAAB3Nza... dummy_key"
        owner: "{{ test_user }}"
        group: "{{ test_user }}"
        mode: '0600'

    - name: Apply illegal permissions to .ssh directory
      ansible.builtin.file:
        path: "/home/{{ test_user }}/.ssh"
        mode: '0777'