# Prompt Example: The MariaDB service on <ip> won't start. I suspect it might be a disk issue,
# but even after checking that, it still won't stay running. Can you do a full diagnosis and fix all the blockers?
---
- name: "Scenario 5: Cascading DB failure (Disk + Permissions)"
  hosts: all
  become: yes
  tasks:
    - name: Ensure MariaDB is installed
      ansible.builtin.package:
        name: mariadb-server
        state: present
        releasever: "10"

    - name: Initialize and start MariaDB first
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Wait for MariaDB to fully initialize
      ansible.builtin.pause:
        seconds: 5

    - name: Stop MariaDB before breaking it
      ansible.builtin.systemd:
        name: mariadb
        state: stopped

    - name: Fill disk until full using fallocate
      ansible.builtin.shell: |
        AVAIL=$(df -B1 --output=avail /var/lib/mysql | tail -1)
        fallocate -l $AVAIL /var/lib/mysql/DISK_HOG || true
      args:
        executable: /bin/bash

    - name: Break log directory ownership
      ansible.builtin.file:
        path: /var/log/mariadb
        owner: root
        group: root
        state: directory

    - name: Attempt to start MariaDB
      ansible.builtin.systemd:
        name: mariadb
        state: started
      failed_when: false
